name: Apple Stock Monitor

on:
  schedule:
    # 5分おきに実行 (GitHub Actionsの制約により遅延が発生する場合があります)
    - cron: '*/5 * * * *'
  workflow_dispatch: # 手動実行も可能にする

jobs:
  check-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run stock monitor
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # 1回だけチェックを実行するスクリプトとして呼び出す
          python apple_stock_monitor_once.py
